[package]
name = "echo-program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.3"
solana-program = "1.10.3"
thiserror = "1.0.30"

[lib]
crate-type = ["cdylib", "lib"]
